version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: javieraguerocl/docker-php8.2-with-db-extensions
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      COMPOSER_MEMORY_LIMIT: -1
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./Docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - default

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default

  #MySQL Service
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: socomarca_wp
      MYSQL_USER: socomarca
      MYSQL_PASSWORD: socomarca123
      MYSQL_ROOT_PASSWORD: root123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

#Docker Networks
networks:
  default:

#Volumes
volumes:
  mysql_data:
    driver: local
